name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build and Start Stack
      run: |
        docker-compose up -d --build
        
 
        
    - name: Check Frontend availability
      run: |
        timeout 60s bash -c 'until curl --silent --fail http://localhost:3001; do echo "Waiting for Frontend..."; sleep 2; done'
        echo "Frontend is up!"
        
    - name: Show Running Containers
      if: failure()
      run: docker ps -a

    - name: Show Logs
      if: failure()
      run: docker-compose logs
      
    - name: Teardown
      run: docker-compose down
